apiVersion: v1
kind: Namespace
metadata:
  name: hungth-project
--- 
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: hungth-project
  name: hungth-daemonset
  labels:
      app: fluentd
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluentd/fluentd:v1.11-debian-1
          resources:
            limits:
              memory: 200Mi
              cpu: 128Mi
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: runlog
            mountPath: /var/lib/docker/containers
            readOnly: true
      volumes:
          - name: /var/log
            hostPath: 
              path: /var/log
          - name: runlog
            hostPath:
              path: /var/lib/docker/containers

#use case for monitoring job, logging job
 
      