apiVersion: batch/v1
kind: Job
metadata:
  name: hungth-job
  namespace: hungth-project
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:
      labels:
        app: hungth-demo
    spec:
      containers:
      - name: hungth-demo
        image: perl
        command: ["echo", "Hello, Hungth!!!!"]
      restartPolicy: Never
