apiVersion: v1
kind: Service
metadata:
  namespace: hungth-project
  name: demo-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx 
  ports:
    - protocol: TCP
      port: 2024 
      targetPort: 80 
  type: ClusterIP 